### PR TITLE
Test fedora

### PR DESCRIPTION
**Pull request by ekilmer**
Based on #25

### CODE REVIEW

**Comment by ekilmer** [comment]
Unfortunately, Github Actions does not have a VM running for Fedora, so I've converted the CI to use Docker images/containers to build and run tests.

It does take a little bit longer since we have to install a bunch of dependencies each time, but I think it'll be okay since it's still under 5 mins for build and test to complete.

If we _really_ wanted faster builds, we could potentially set up a system where we build a docker image with the required dependencies, upload it to Dockerhub, and then pull that one down (instead of generic `ubuntu:latest` and `fedora:latest`). However, that would require us to update the images at least once a week (probably not too hard with Github Actions, though), so that we faithfully test what a new user would experience on each distro.

**Comment by haampie** [comment]
Hm, interesting:

```
libc.so.6 not found
```

does not seem right. Could as well be a bug in libtree, will investigate a bit later!

**Comment by ekilmer** [comment]
Would you like me to rebase this on top of `master` now that the other PRs are merged?

**Comment by haampie** [comment]
Rebased it for you and added a commit that adds `/lib64` and `/usr/lib64` as default search paths like mentioned in `man ld.so`. This is still not entirely correct, since we're just searching a subset of the paths listed in the debug info of #27, but it could be difficult to retrieve all the paths, since they seem to be compiled hard-coded in the dynamic linker. Do you think this is sufficiently correct @ekilmer?

**Comment by haampie** [comment]
Thanks for all the efforts btw, very much appreciated!

**Comment by ekilmer** [comment]
This looks good to me! Thank you!

**Pull request merged**
