### PR TITLE
Match automake variable names

### PR DESCRIPTION
**Pull request by ismaell**
Also, allow overriding the manual pages directory.

### CODE REVIEW

**Comment by haampie** [comment]
hm, this is a somewhat breaking change. Can you initialize `prefix` with `PREFIX`?

**Comment by ismaell** [comment]
> Can you initialize `prefix` with `PREFIX`? 

done.

> Also whatever is defined in `Make.user` will be overridden, right?

yes, if you want contents of `Make.user` to take precedence, I can just move it after the variables (using `?=` instead is a little bit dangerous, IMHO). Then the order would be: arguments, `Make.user`, `Makefile`.

**Comment by ismaell** [comment]
Ping.

**Review by haampie — APPROVED** [review]

**Comment by iluceno** [comment]
Thanks.

**Comment by iluceno** [comment]
BTW, this is required by pkgsrc and other buildsystems to install without hacks. See: 
<https://mail-index.netbsd.org/tech-pkg/2022/03/22/msg026097.html>. Now it's possible to specify: `mandir=${PKGMANDIR}` to get manpages correctly installed.

So I'm hoping you make a release including this soon :).

BTW, would you consider a GNU-style `configure` script to produce `Make.user`?

**Comment by haampie** [comment]
It's in 3.0.4 and 3.1.1 :) I was hoping to keep things very simple, so there must be a compelling reason to want a configure script

**Comment by ismaell** [comment]
> It's in 3.0.4 and 3.1.1 :) I was hoping to keep things very simple, so there must be a compelling reason to want a configure script

No, you included PR #75 but not this one.

**Comment by ismaell** [comment]
On 13/May/2022 07:38, Harmen Stoppels wrote:
> It's in 3.0.4 and 3.1.1 :) I was hoping to keep things very simple,
> so there must be a compelling reason to want a configure script

No, it isn't, I checked :).

**Comment by ismaell** [comment]
Ping. So, the `pkgsrc` package is still waiting for this to be included in a release...

**Pull request merged**
