### PR TITLE
More buildsystem portability fixes

### PR DESCRIPTION
**Pull request by ismaell**
This makes it fully usabe with `bmake`.

### CODE REVIEW

**Comment by haampie** [comment]
Can you rebase once more on master s.t. CI runs on this PR?

**Comment by ismaell** [comment]
I think I handled everything now. It should build fine on NetBSD now w/o GNU make. I'll test that next.

**Comment by haampie** [comment]
Thanks, let me know if it works for you, then I'll merge.

**Comment by ismaell** [comment]
> Thanks, let me know if it works for you, then I'll merge.

It works with `bmake` on Linux, so the buildsystem side works.

**Comment by ismaell** [comment]
ah, it's already there in pkgsrc, so that means it works :).

**Comment by haampie** [comment]
Thanks! I've added it to the 3.0 and 3.1 branches.

**Pull request merged**
